(() => {
const items=[...document.querySelectorAll('.item')],counter=document.querySelector('#count'),visible=document.querySelector('#visible'),filterButtons=[...document.querySelectorAll('.filters button')];
const portal=document.querySelector('#portal-intro'),portalEnter=document.querySelector('#portal-enter'),accountControl=document.querySelector('#account-control');
const gate=document.querySelector('#auth-panel'),form=document.querySelector('#auth-form'),email=document.querySelector('#auth-email'),password=document.querySelector('#auth-password'),username=document.querySelector('#auth-username'),confirmPassword=document.querySelector('#auth-confirm-password'),terms=document.querySelector('#auth-terms'),submit=document.querySelector('#auth-submit'),switcher=document.querySelector('#auth-switch'),modeLabel=document.querySelector('#auth-mode-label'),logout=document.querySelector('#auth-logout'),message=document.querySelector('#auth-message'),syncStatus=document.querySelector('#sync-status'),termsModal=document.querySelector('#terms-modal');
const storageKey='doomlist-watched-v1';let filter='all',isSignup=false,supabase=null,currentUser=null,watched=loadLocal();
function loadLocal(){try{return JSON.parse(localStorage.getItem(storageKey)||'{}')}catch{return {}}}
function saveLocal(){try{localStorage.setItem(storageKey,JSON.stringify(watched))}catch{}}
function setMessage(t,error=false){if(message){message.textContent=t;message.classList.toggle('error',error)}}
function setSync(t,online=false){if(!syncStatus)return;const s=syncStatus.querySelector('span');if(s)s.textContent=t;syncStatus.classList.toggle('online',online)}
function watchedCount(){return items.filter(i=>watched[i.dataset.id||i.querySelector('.num')?.textContent.trim()]).length}
function render(next=filter){filter=next;let n=0;items.forEach(item=>{const show=filter==='all'||item.dataset.type===filter;n+=show?1:0;item.classList.toggle('hidden',!show);const id=item.dataset.id||item.querySelector('.num')?.textContent.trim(),cb=item.querySelector('.watched-toggle input');if(cb)cb.checked=Boolean(watched[id]);item.classList.toggle('is-watched',Boolean(watched[id]))});if(counter)counter.textContent=String(n).padStart(2,'0');if(visible)visible.textContent=watchedCount()+' / '+items.length+' WATCHED'}
function setAuth(user){currentUser=user||null;gate?.classList.toggle('is-authenticated',!!currentUser);document.body.classList.toggle('auth-locked',!currentUser);logout?.classList.toggle('hidden',!currentUser);submit?.classList.toggle('hidden',!!currentUser);switcher?.classList.toggle('hidden',!!currentUser);accountControl?.classList.toggle('hidden',!currentUser);if(accountControl)accountControl.innerHTML=currentUser?'SIGN OUT <span>↗</span>':'ACCOUNT <span>↗</span>';
if(currentUser){form?.querySelectorAll('label,input').forEach(el=>{if(el!==terms)el.classList.add('hidden')});document.querySelectorAll('.signup-only').forEach(el=>el.classList.add('hidden'));const h=document.querySelector('#auth-title');if(h)h.innerHTML='WELCOME <em>BACK</em>';setSync('CLOUD SYNC ACTIVE',true);loadCloud()}else{form?.querySelectorAll('label,input').forEach(el=>el.classList.remove('hidden'));setSignup(isSignup);setSync(supabase?'SECURE CONNECTION':'CONNECTION UNAVAILABLE');if(!supabase)setMessage('The account service is unavailable. Please try again later.',true);else setMessage('Sign in or create an account to continue.')}}
async function loadCloud(){if(!supabase||!currentUser)return;setSync('SYNCING…');const{data,error}=await supabase.from('watch_progress').select('item_id,watched');if(error){setMessage('Could not load cloud progress. Please try again.',true);setSync('SYNC ERROR');return}const cloud={};(data||[]).forEach(r=>cloud[r.item_id]=r.watched);watched={...watched,...cloud};saveLocal();render();setSync('CLOUD SYNC ACTIVE',true);setMessage('SYNCED · '+watchedCount()+'/'+items.length+' WATCHED')}
async function syncItem(id,value){if(!supabase||!currentUser)return;const{error}=await supabase.from('watch_progress').upsert({user_id:currentUser.id,item_id:id,watched:value,updated_at:new Date().toISOString()},{onConflict:'user_id,item_id'});if(error){setMessage('Saved on this device, but cloud sync failed. '+error.message,true);setSync('SYNC ERROR')}else setMessage('SYNCED · '+watchedCount()+'/'+items.length+' WATCHED')}
function setSignup(next){isSignup=next;document.querySelectorAll('.signup-only').forEach(el=>el.classList.toggle('hidden',!next));if(username)username.required=next;if(confirmPassword)confirmPassword.required=next;if(terms)terms.required=next;if(password){password.autocomplete=next?'new-password':'current-password';password.minLength=8}if(submit)submit.innerHTML=next?'CREATE ACCOUNT <b>✦</b>':'SIGN IN <b>✦</b>';if(switcher)switcher.textContent=next?'ALREADY HAVE AN ACCOUNT? SIGN IN':'CREATE AN ACCOUNT';if(modeLabel)modeLabel.textContent=next?'CREATE ACCOUNT':'SIGN IN';const h=document.querySelector('#auth-title');if(h)h.innerHTML=next?'JOIN THE <em>MULTIVERSE</em>':'WELCOME <em>BACK</em>';if(supabase)setMessage(next?'Create your account to save your watch progress everywhere.':'Sign in to continue to DOOMLIST.')}
items.forEach(item=>{const id=item.querySelector('.num')?.textContent.trim();if(!id)return;item.dataset.id=id;if(!item.querySelector('.watched-toggle')){const label=document.createElement('label');label.className='watched-toggle';label.innerHTML='<input type="checkbox" aria-label="Mark as watched"><span>WATCHED</span>';item.insertBefore(label,item.querySelector('.priority')||null);label.querySelector('input').addEventListener('change',async e=>{watched[id]=e.target.checked;saveLocal();render();await syncItem(id,e.target.checked)})}});
filterButtons.forEach(b=>b.addEventListener('click',()=>{filterButtons.forEach(x=>x.classList.remove('selected'));b.classList.add('selected');render(b.dataset.filter)}));
switcher?.addEventListener('click',()=>setSignup(!isSignup));
async function signOut(){if(!supabase)return;const{error}=await supabase.auth.signOut();if(error)setMessage(error.message,true)}
logout?.addEventListener('click',signOut);
accountControl?.addEventListener('click',signOut);
const portalStage=document.querySelector('#portal-stage');
let portalPointerFrame=0;
portal?.addEventListener('pointermove',e=>{if(e.pointerType==='touch'||portal.classList.contains('entering'))return;const rect=portal.getBoundingClientRect(),x=(e.clientX-rect.left)/rect.width-.5,y=(e.clientY-rect.top)/rect.height-.5;cancelAnimationFrame(portalPointerFrame);portalPointerFrame=requestAnimationFrame(()=>{portal.style.setProperty('--pointer-x',x.toFixed(3));portal.style.setProperty('--pointer-y',y.toFixed(3));if(portalStage){portalStage.style.setProperty('--tilt-x',(-y*8).toFixed(2)+'deg');portalStage.style.setProperty('--tilt-y',(x*10).toFixed(2)+'deg')}})});
portal?.addEventListener('pointerleave',()=>{portal.style.setProperty('--pointer-x','0');portal.style.setProperty('--pointer-y','0');if(portalStage){portalStage.style.setProperty('--tilt-x','0deg');portalStage.style.setProperty('--tilt-y','0deg')}});
portalEnter?.addEventListener('click',()=>{if(portal?.classList.contains('entering'))return;portal?.classList.add('entering');document.body.classList.add('portal-entering');portalEnter.setAttribute('aria-label','Entering DOOMLIST');window.setTimeout(()=>{portal?.classList.add('portal-gone');document.body.classList.remove('portal-entering');window.setTimeout(()=>portal?.remove(),900)},1450)});
form?.addEventListener('submit',async e=>{e.preventDefault();if(!supabase){setMessage('The account service is unavailable. Please try again later.',true);return}const mail=email.value.trim(),pass=password.value;if(isSignup){if(!username.value.trim()||username.value.trim().length<3){setMessage('Username must contain at least 3 characters.',true);return}if(!/^[A-Za-z0-9_.-]+$/.test(username.value.trim())){setMessage('Use only letters, numbers, dots, underscores or hyphens in your username.',true);return}if(pass!==confirmPassword.value){setMessage('The passwords do not match.',true);confirmPassword.focus();return}if(!terms.checked){setMessage('Please accept the Terms of Service.',true);return}}submit.disabled=true;try{const result=isSignup?await supabase.auth.signUp({email:mail,password:pass,options:{data:{username:username.value.trim()}}}):await supabase.auth.signInWithPassword({email:mail,password:pass});if(result.error)throw result.error;if(isSignup&&!result.data.session)setMessage('Account created! Check your email to confirm it. After confirmation, you can sign in.');else{setMessage(isSignup?'Account created! Signing you in…':'Signed in! Loading your watchlist…');setAuth(result.data.user)}}catch(err){setMessage(err.message||'Authentication failed.',true)}finally{submit.disabled=false}});
document.querySelectorAll('.terms-open').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();termsModal?.classList.remove('hidden')}));document.querySelectorAll('.terms-close').forEach(el=>el.addEventListener('click',()=>termsModal?.classList.add('hidden')));termsModal?.addEventListener('click',e=>{if(e.target===termsModal)termsModal.classList.add('hidden')});document.addEventListener('keydown',e=>{if(e.key==='Escape')termsModal?.classList.add('hidden')});document.querySelector('.auth-brand')?.addEventListener('click',e=>e.preventDefault());
if(window.DOOMLIST_SUPABASE_URL&&window.DOOMLIST_SUPABASE_KEY&&window.supabase?.createClient){supabase=window.supabase.createClient(window.DOOMLIST_SUPABASE_URL,window.DOOMLIST_SUPABASE_KEY);supabase.auth.onAuthStateChange((_event,session)=>setAuth(session?.user||null));supabase.auth.getSession().then(({data,error})=>{if(error)setMessage('Could not check your session. Please refresh.',true);setAuth(data?.session?.user||null)})}else{document.body.classList.add('auth-locked');setSync('CONNECTION UNAVAILABLE');setMessage('The account service is unavailable. Please try again later.',true)}
render();
})();